---
title: "Práctica 1"
author: "Oriol, Víctor, Miriam, Ulises"
date: "2025-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Data Science
## Pregunta 1

**De las siguientes preguntas, clasifica cada una como descriptiva, exploratoria, inferencia, predictiva o causal, y razona brevemente (una frase) el porqué:**

**1. Dado un registro de vehículos que circulan por una autopista, disponemos de su marca y modelo, país de matriculación, y tipo de vehículo (por número de ruedas). Con tal de ajustar precios de los peajes, ¿Cuántos vehículos tenemos por tipo? ¿Cuál es el tipo más frecuente? ¿De qué países tenemos más vehículos?**
    
    Descriptiva, ya que estamos buscando estadíticas del total de vehículos según sus características para hacer un ajuste del precio de los peajes.


**2. Dado un registro de visualizaciones de un servicio de video-on-demand, donde disponemos de los datos del usuario, de la película seleccionada, fecha de visualización y categoría de la película, queremos saber ¿Hay alguna preferencia en cuanto a género literario según los usuarios y su rango de edad?**

    Exploratoria, ya que se está relacionando el rango de edad del usuario con la preferencia del género cinematográfico.


**3. Dado un registro de peticiones a un sitio web, vemos que las peticiones que provienen de una red de telefonía concreta acostumbran a ser incorrectas y provocarnos errores de servicio. ¿Podemos determinar si en el futuro, los próximos mensajes de esa red seguirán dando problemas? ¿Hemos notado el mismo efecto en otras redes de telefonía?**

    Predictiva, ya que intentamos predecir un comportamiento futuro a partir de un registro de peticiones ya realizadas a un sitio web.


**4. Dado los registros de usuarios de un servicio de compras por internet, los usuarios pueden agruparse por preferencias de productos comprados. Queremos saber si ¿Es posible que, dado un usuario al azar y según su historial, pueda ser directamente asignado a un o diversos grupos?**

    Predictiva, porque a partir de los datos que tenemos del historial del usuario, le estamos asignando a un o diversos grupos.

    
## Pregunta 2:

**Considera el siguiente escenario:<br>**
**Sabemos que un usuario de nuestra red empresarial ha estado usando esta para fines no relacionados con el trabajo, como por ejemplo tener un servicio web no autorizado abierto a la red (otros usuarios tienen servicios web activados y autorizados). No queremos tener que rastrear los puertos de cada PC, y sabemos que la actividad puede haber cesado. Pero podemos acceder a los registros de conexiones TCP de cada máquina de cada trabajador (hacia donde abre conexión un PC concreto). Sabemos que nuestros clientes se conectan desde lugares remotos de forma legítima, como parte de nuestro negocio, y que un trabajador puede haber habilitado temporalmente servicios de prueba. Nuestro objetivo es reducir lo posible la lista de posibles culpables, con tal de explicarles que por favor no expongan nuestros sistemas sin permiso de los operadores o la dirección.**

**Explica con detalle cómo se podría proceder al análisis y resolución del problema mediante Data Science, indicando de donde se obtendrían los datos, qué tratamiento deberían recibir, qué preguntas hacerse para resolver el problema, qué datos y gráficos se obtendrían, y cómo se comunicarían estos.**

    Obtendríamos los datos de los registros de conexiones TCP salientes por máquina, por ejemplo de los logs del firewall.
    
    Para tratar este conjunto de conexiones TCP primero tendríamos que parsear los datos y normalizarlos para poder trabajar con ellos de forma rápida y eficiente. Además, tendremos que eliminar registros incompletos, asociar cada IP interna a un usuario o equipo concreto. 
    
    Para resolver el problema podrían hacerse estas preguntas:
      -¿Qué patrón deja un servicio web expuesto?
      -¿Qué PCs tienen un número alto de IPs externas únicas conectadas?
      -¿Qué PCs reciben conexiones desde múltiples países?
      -¿Qué PCs reciben conexiones fuera de horario laboral?

    Con este análisis podríamos obtener el siguiente listado de gráficos:
      -Histograma: para poder analizar qué IPs externas únicas hay por PC
      -Serie temporal: para observar número de conexiones por hora
      -Mapa geográfico: para determinar el origen de IPs externas por cada PC
      -Heatmap: para poder ver los PC con mayorn número de uso de sus puertos
    
    Para comunicar todo estos datos y gráficos a los trabajadores lo haríamos de una forma no acusatoria, buscando su colaboración mostrandóle los motivos por los cuales su comportamiento no es el adecuado y podría comportar riesgos para la empresa. 
    
    Por otro lado, para comunicarsélos a los directivos haríamos uso de estos gráficos con mensajes claros demostrar las conclusiones y soluciones a las que se han llegado con el análisis.





